/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sample.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import sample.model.Sample;
import sample.model.SampleModel;
import sample.model.SampleSoap;

/**
 * The base model implementation for the Sample service. Represents a row in the &quot;SAMPLE_Sample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SampleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleImpl
 * @generated
 */
@JSON(strict = true)
public class SampleModelImpl
	extends BaseModelImpl<Sample> implements SampleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample model instance should use the <code>Sample</code> interface instead.
	 */
	public static final String TABLE_NAME = "SAMPLE_Sample";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"sampleId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"field1", Types.VARCHAR}, {"field2", Types.BOOLEAN},
		{"field3", Types.INTEGER}, {"field4", Types.TIMESTAMP},
		{"field5", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sampleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("field2", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("field3", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("field4", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field5", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SAMPLE_Sample (uuid_ VARCHAR(75) null,sampleId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,field1 VARCHAR(75) null,field2 BOOLEAN,field3 INTEGER,field4 DATE null,field5 VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table SAMPLE_Sample";

	public static final String ORDER_BY_JPQL = " ORDER BY sample.field1 ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SAMPLE_Sample.field1 ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long FIELD2_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long FIELD1_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Sample toModel(SampleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Sample model = new SampleImpl();

		model.setUuid(soapModel.getUuid());
		model.setSampleId(soapModel.getSampleId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setField1(soapModel.getField1());
		model.setField2(soapModel.isField2());
		model.setField3(soapModel.getField3());
		model.setField4(soapModel.getField4());
		model.setField5(soapModel.getField5());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Sample> toModels(SampleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Sample> models = new ArrayList<Sample>(soapModels.length);

		for (SampleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SampleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sampleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSampleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sampleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Sample.class;
	}

	@Override
	public String getModelClassName() {
		return Sample.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Sample, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Sample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sample, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Sample)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Sample, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Sample, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Sample)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Sample, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Sample, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Sample>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Sample.class.getClassLoader(), Sample.class, ModelWrapper.class);

		try {
			Constructor<Sample> constructor =
				(Constructor<Sample>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Sample, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Sample, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Sample, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Sample, Object>>();
		Map<String, BiConsumer<Sample, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Sample, ?>>();

		attributeGetterFunctions.put("uuid", Sample::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Sample, String>)Sample::setUuid);
		attributeGetterFunctions.put("sampleId", Sample::getSampleId);
		attributeSetterBiConsumers.put(
			"sampleId", (BiConsumer<Sample, Long>)Sample::setSampleId);
		attributeGetterFunctions.put("groupId", Sample::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Sample, Long>)Sample::setGroupId);
		attributeGetterFunctions.put("companyId", Sample::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Sample, Long>)Sample::setCompanyId);
		attributeGetterFunctions.put("userId", Sample::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Sample, Long>)Sample::setUserId);
		attributeGetterFunctions.put("userName", Sample::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Sample, String>)Sample::setUserName);
		attributeGetterFunctions.put("createDate", Sample::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Sample, Date>)Sample::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Sample::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Sample, Date>)Sample::setModifiedDate);
		attributeGetterFunctions.put("field1", Sample::getField1);
		attributeSetterBiConsumers.put(
			"field1", (BiConsumer<Sample, String>)Sample::setField1);
		attributeGetterFunctions.put("field2", Sample::getField2);
		attributeSetterBiConsumers.put(
			"field2", (BiConsumer<Sample, Boolean>)Sample::setField2);
		attributeGetterFunctions.put("field3", Sample::getField3);
		attributeSetterBiConsumers.put(
			"field3", (BiConsumer<Sample, Integer>)Sample::setField3);
		attributeGetterFunctions.put("field4", Sample::getField4);
		attributeSetterBiConsumers.put(
			"field4", (BiConsumer<Sample, Date>)Sample::setField4);
		attributeGetterFunctions.put("field5", Sample::getField5);
		attributeSetterBiConsumers.put(
			"field5", (BiConsumer<Sample, String>)Sample::setField5);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSampleId() {
		return _sampleId;
	}

	@Override
	public void setSampleId(long sampleId) {
		_sampleId = sampleId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getField1() {
		if (_field1 == null) {
			return "";
		}
		else {
			return _field1;
		}
	}

	@Override
	public void setField1(String field1) {
		_columnBitmask = -1L;

		_field1 = field1;
	}

	@JSON
	@Override
	public boolean getField2() {
		return _field2;
	}

	@JSON
	@Override
	public boolean isField2() {
		return _field2;
	}

	@Override
	public void setField2(boolean field2) {
		_columnBitmask |= FIELD2_COLUMN_BITMASK;

		if (!_setOriginalField2) {
			_setOriginalField2 = true;

			_originalField2 = _field2;
		}

		_field2 = field2;
	}

	public boolean getOriginalField2() {
		return _originalField2;
	}

	@JSON
	@Override
	public int getField3() {
		return _field3;
	}

	@Override
	public void setField3(int field3) {
		_field3 = field3;
	}

	@JSON
	@Override
	public Date getField4() {
		return _field4;
	}

	@Override
	public void setField4(Date field4) {
		_field4 = field4;
	}

	@JSON
	@Override
	public String getField5() {
		if (_field5 == null) {
			return "";
		}
		else {
			return _field5;
		}
	}

	@Override
	public void setField5(String field5) {
		_field5 = field5;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Sample.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Sample.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sample toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Sample>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SampleImpl sampleImpl = new SampleImpl();

		sampleImpl.setUuid(getUuid());
		sampleImpl.setSampleId(getSampleId());
		sampleImpl.setGroupId(getGroupId());
		sampleImpl.setCompanyId(getCompanyId());
		sampleImpl.setUserId(getUserId());
		sampleImpl.setUserName(getUserName());
		sampleImpl.setCreateDate(getCreateDate());
		sampleImpl.setModifiedDate(getModifiedDate());
		sampleImpl.setField1(getField1());
		sampleImpl.setField2(isField2());
		sampleImpl.setField3(getField3());
		sampleImpl.setField4(getField4());
		sampleImpl.setField5(getField5());

		sampleImpl.resetOriginalValues();

		return sampleImpl;
	}

	@Override
	public int compareTo(Sample sample) {
		int value = 0;

		value = getField1().compareTo(sample.getField1());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Sample)) {
			return false;
		}

		Sample sample = (Sample)object;

		long primaryKey = sample.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		SampleModelImpl sampleModelImpl = this;

		sampleModelImpl._originalUuid = sampleModelImpl._uuid;

		sampleModelImpl._originalGroupId = sampleModelImpl._groupId;

		sampleModelImpl._setOriginalGroupId = false;

		sampleModelImpl._originalCompanyId = sampleModelImpl._companyId;

		sampleModelImpl._setOriginalCompanyId = false;

		sampleModelImpl._setModifiedDate = false;

		sampleModelImpl._originalField2 = sampleModelImpl._field2;

		sampleModelImpl._setOriginalField2 = false;

		sampleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Sample> toCacheModel() {
		SampleCacheModel sampleCacheModel = new SampleCacheModel();

		sampleCacheModel.uuid = getUuid();

		String uuid = sampleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			sampleCacheModel.uuid = null;
		}

		sampleCacheModel.sampleId = getSampleId();

		sampleCacheModel.groupId = getGroupId();

		sampleCacheModel.companyId = getCompanyId();

		sampleCacheModel.userId = getUserId();

		sampleCacheModel.userName = getUserName();

		String userName = sampleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sampleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sampleCacheModel.createDate = createDate.getTime();
		}
		else {
			sampleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sampleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sampleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sampleCacheModel.field1 = getField1();

		String field1 = sampleCacheModel.field1;

		if ((field1 != null) && (field1.length() == 0)) {
			sampleCacheModel.field1 = null;
		}

		sampleCacheModel.field2 = isField2();

		sampleCacheModel.field3 = getField3();

		Date field4 = getField4();

		if (field4 != null) {
			sampleCacheModel.field4 = field4.getTime();
		}
		else {
			sampleCacheModel.field4 = Long.MIN_VALUE;
		}

		sampleCacheModel.field5 = getField5();

		String field5 = sampleCacheModel.field5;

		if ((field5 != null) && (field5.length() == 0)) {
			sampleCacheModel.field5 = null;
		}

		return sampleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Sample, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Sample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sample, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Sample)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Sample, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Sample, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sample, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Sample)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Sample>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _sampleId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _field1;
	private boolean _field2;
	private boolean _originalField2;
	private boolean _setOriginalField2;
	private int _field3;
	private Date _field4;
	private String _field5;
	private long _columnBitmask;
	private Sample _escapedModel;

}